$(document).ready(function(){var t=1,n=0,a=0,e=[];function i(t){$(".blog_container").empty();for(var n=(t-1)*5,a=n+5,i=n;i<a;i++)e[i]&&$(".blog_container").append(e[i])}function o(){$("#blog .pagination button").removeClass("current"),$("#blog .pagination button").eq(t-1).addClass("current"),$("#blog .pagination button:first").prop("disabled",1===t),$("#blog .pagination button:last").prop("disabled",t===a)}$.ajax({url:"/include/content/blog.xml",dataType:"xml",success:function(r){n=$(r).find("item").length,$(r).find("item").each(function(t){var n,a=$(this).find("title").text(),i=$(this).find("link").text(),o=new Date($(this).find("pubDate").text()),r=$(this).find("description").text(),l=$(this).find("labels label").map(function(){return $(this).text()}).get(),c=`
                    <a href="${i}" target="_blank" class="blog-post" data-topic-1="${l[0]}" data-topic-2="${l[1]}" data-topic-3="${l[2]}" rel="noopener follow">
                        <time datetime="${o.toISOString()}">${o.toLocaleDateString("en-US",{weekday:"short",year:"numeric",month:"short",day:"numeric"}).replace(",","")}</time>
                        <h2>${a}</h2>
                        <p>${r}</p>
                        <div class="blog-labels-container">
                            ${l.map(function(t){return"<label><div></div><span>"+t+"</span></label>"}).join("")}
                        </div>
                    </a>
                `;e.push(c)}),i(t),function e(){$("#blog .pagination").empty(),a=Math.ceil(n/5);for(var r=1;r<=a;r++){var l=r===t?"current":"",c=$("<button></button>").addClass(l).text(r);c.on("click",{pageNumber:r},function(n){i(t=n.data.pageNumber),o()}),$("#blog .pagination").append(c)}}()},error:function(){console.error("No se pudo cargar el archivo XML.")}}),$(".topics-container").slick({variableWidth:!0,infinite:!0,arrows:!1,autoplay:!0,autoplaySpeed:1e3,pauseOnFocus:!1,mobileFirst:!0,accessibility:!0,focusOnSelect:!1,lazyLoad:"ondemand",pauseOnHover:!1})});