$(document).ready(function(){var e=1,t=[],n=[];function r(){var r=$("#filter-year-select").val(),a=$('input[name="filters-type"]:checked').attr("id").split("-").pop();n=t.filter(function(e){var t="all"===r||e.year.toString()===r,n="all"===a||e.category.toLowerCase()===a;return t&&n}),i(e=1),o()}function i(e){$(".writeups_container").addClass("fade-out"),setTimeout(function(){if($(".writeups_container").empty(),0===n.length)$(".writeups_container").append(`
    <div class="filters-without-results">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/></svg>
        <p>No results found for these filters</p>
    </div>
`);else{var t=(e-1)*5;n.slice(t,t+5).forEach(function(e){$(".writeups_container").append(e.html)})}$(".writeups_container").removeClass("fade-out")},500)}function o(){$("#prevButton").prop("disabled",1===e),$("#nextButton").prop("disabled",e===Math.ceil(n.length/5))}$("#prevButton").on("click",function(){e>1&&(i(--e),o())}),$("#nextButton").on("click",function(){e<Math.ceil(n.length/5)&&(i(++e),o())}),$("#filter-year-select").on("change",r),$('input[name="filters-type"]').on("change",r),$.ajax({url:"/include/content/writeup.xml",dataType:"xml",success:function(e){$(e).find("item").each(function(){var e=$(this).find("title").text(),n=$(this).find("link").attr("href"),r=new Date($(this).find("pubDate").text()),i=$(this).find("category").text(),o=`
        <a href="${n}" data-year="${r.getFullYear()}" data-category="${i}" target="_blank" rel="noopener follow">
            <h2>${e} [ ${i} ]</h2>
            <time datetime="${r.toISOString()}">${r.toLocaleDateString("en-US",{weekday:"short",year:"numeric",month:"short",day:"numeric"}).replace(",","")}</time>
        </a>
    `;t.push({html:o,year:r.getFullYear(),category:i})}),r()},error:function(){console.error("Error fetching the XML file.")}})});