/* <!-- 
#   ___  ____  __   
#  / __)(  _ \(  )  
# ( (__  )___/ )(__  (code by cpadlab)
#  \___)(__)  (____)

# Author >> Carlos Padilla
# Proyect >> CPWvFeb24 (Carlos Padilla Web 2024 May Update)
# Download Code >> https://github.com/cpadlab/cpadlab.github.io
# Follow me >> https://twitter.com/cpadlab
--> */

export function sectionAbout(){function e(){document.getElementById("about-text").innerText="In September of 2021, I started in the world of computer science by studying an intermediate degree in Microcomputer Systems and Networks to begin to follow that slight dream I had at that time. As time went by, at the end of 2022, I decided to learn programming in a self-taught way, because until then, my knowledge did not allow me to develop myself more as a professional. I decided to learn the Python programming language, because I had heard that it was widely used in cybersecurity and although I barely knew anything about this art, I set it as a goal. As soon as 2023 started, I went to work as an Erasmus student to do my internship in Italy, as a systems technician. And it was there that I started to love offensive cybersecurity. During my stay in the country, I was studying the eJPT until mid-July, when I took the exam and passed the certification. Now I have new challenges, new projects, new dreams, you know what they are?",$("#clb-es").removeClass("clb-selected"),$("#clb-en").addClass("clb-selected"),$("#about-text").moreLess({wordsCount:100,moreLabel:"... Read More",lessLabel:" Read Less",moreClass:"read-more-link",lessClass:"read-less-link"})}document.getElementById("clb-es").addEventListener("click",function(){$("#clb-es").addClass("clb-selected"),$("#clb-en").removeClass("clb-selected"),document.getElementById("about-text").innerText="En septiembre de 2021, me inici\xe9 en el mundo de la inform\xe1tica estudiando un grado medio en Sistemas Microinform\xe1ticos y Redes para empezar a seguir ese peque\xf1o sue\xf1o que ten\xeda en ese momento. Con el paso del tiempo, a finales de 2022, decid\xed aprender programaci\xf3n de forma autodidacta, ya que hasta entonces, mis conocimientos no me permit\xedan desarrollarme m\xe1s como profesional. Decid\xed aprender el lenguaje de programaci\xf3n Python, porque hab\xeda o\xeddo que era muy utilizado en ciberseguridad y aunque apenas sab\xeda nada de este arte, me lo puse como objetivo. Nada m\xe1s empezar 2023, me fui de Erasmus a hacer pr\xe1cticas a Italia, como t\xe9cnico de sistemas. Y fue all\xed donde empec\xe9 a amar la ciberseguridad ofensiva. Durante mi estancia en el pa\xeds, estuve estudiando el eJPT hasta mediados de julio, cuando hice el examen y aprob\xe9 la certificaci\xf3n. Ahora tengo nuevos retos, nuevos proyectos, nuevos sue\xf1os, \xbfsabes cu\xe1les son?",$("#about-text").moreLess({wordsCount:100,moreLabel:"... Leer M\xe1s",lessLabel:" Leer Menos",moreClass:"read-more-link",lessClass:"read-less-link"})}),document.getElementById("clb-en").addEventListener("click",function(){e()}),e(),document.getElementById("clb-en").addEventListener("click",function(){e()})}